import type { Lesson } from './types';

export interface LessonExercise {
  id: string;
  title: string;
  kind: 'breathing' | 'repeat' | 'reading' | 'conversation' | 'reflection';
  description: string;
  instructions?: string[];
  phrases?: string[];
  readText?: string;
  prompt?: string;
  durationHint?: string;
  repeatCount?: number;
  speakText?: string;
}

export interface UnitLessonContent {
  id: string;
  title: string;
  goal: string;
  description: string;
  durationMins: number;
  coachTip?: string;
  techniqueReminders?: string[];
  exercises: LessonExercise[];
  reflectionPrompt: string;
}

export interface UnitContent {
  id: string;
  title: string;
  theme: string;
  goal: string;
  description: string;
  lessons: UnitLessonContent[];
}

export const units: UnitContent[] = [
  {
    id: 'unit-1',
    title: 'Unit 1',
    theme: 'Awareness & Relaxed Breathing',
    goal: 'Learn to stay calm before speaking and build confidence using slow, relaxed speech.',
    description: 'A gentle first week designed like a real speech-therapy starter sequence.',
    lessons: [
      {
        id: 'unit-1-lesson-1',
        title: 'Lesson 1 — Welcome to LanSpeech',
        goal: 'Learn how relaxed breathing supports easier speech.',
        description: 'Build calm breathing, simple repetition, gentle reading, and mirror speaking.',
        durationMins: 12,
        reflectionPrompt: 'How relaxed did you feel today? Rate yourself from 1 to 5.',
        exercises: [
          {
            id: 'u1-l1-1',
            title: 'Belly Breathing',
            kind: 'breathing',
            description: 'Use your breath to settle your body before speaking.',
            instructions: [
              'Sit comfortably.',
              'Place one hand on your chest and one on your stomach.',
              'Breathe in through your nose for 4 seconds.',
              'Feel only your stomach rise.',
              'Breathe out slowly through your mouth for 6 seconds.',
              'Relax your shoulders.',
            ],
            repeatCount: 10,
            speakText: 'Breathe in slowly and let the breath soften your body.',
          },
          {
            id: 'u1-l1-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Speak slowly and pause briefly between words.',
            phrases: ['Hello', 'Welcome', 'Happy', 'Family', 'Friend', 'Water', 'Today', 'Beautiful', 'Morning', 'Thank you'],
            repeatCount: 5,
            speakText: 'Hello. Welcome. Happy. Family. Friend. Water. Today. Beautiful. Morning. Thank you.',
          },
          {
            id: 'u1-l1-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times with a calm pace.',
            readText: 'Hello. My name is Daniel. Today is a beautiful day. I enjoy talking with people. Every day I become more confident. I take my time when I speak. My voice deserves to be heard.',
            durationHint: 'Read three times',
            speakText: 'Hello. My name is Daniel. Today is a beautiful day.',
          },
          {
            id: 'u1-l1-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Stand in front of a mirror and answer slowly.',
            prompt: 'What is your name? Where do you live? What is one thing you enjoy doing?',
            durationHint: 'Try speaking for one minute.',
            speakText: 'My name is Daniel. I live in a quiet neighborhood. I enjoy walking and reading.',
          },
        ],
      },
      {
        id: 'unit-1-lesson-2',
        title: 'Lesson 2 — Speaking Slowly',
        goal: 'Learn that slowing down makes speech feel more controlled.',
        description: 'Practice softer breathing, calm repetition, and steady pacing.',
        durationMins: 12,
        reflectionPrompt: 'Did slowing down make speaking easier?',
        exercises: [
          {
            id: 'u1-l2-1',
            title: 'Slow Breathing',
            kind: 'breathing',
            description: 'Use a calm rhythm to build a steadier speaking pace.',
            instructions: [
              'Breathe in for 4 seconds.',
              'Pause for 2 seconds.',
              'Breathe out for 6 seconds.',
            ],
            repeatCount: 10,
            speakText: 'Slow breath in, pause, slow breath out.',
          },
          {
            id: 'u1-l2-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Repeat each sentence slowly and gently.',
            phrases: ['Good morning.', 'How are you?', 'My name is John.', 'Thank you.', 'I am happy today.'],
            repeatCount: 5,
            speakText: 'Good morning. How are you? My name is John.',
          },
          {
            id: 'u1-l2-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage slowly and let each phrase land.',
            readText: 'I enjoy learning new things. Every day I become a better communicator. Speaking slowly helps me stay relaxed. I focus on sharing my ideas instead of rushing my words.',
            durationHint: 'Read three times',
            speakText: 'I enjoy learning new things. Every day I become a better communicator.',
          },
          {
            id: 'u1-l2-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Answer aloud and keep your pacing calm.',
            prompt: 'What did you eat today? What is your favorite food? What is your favorite color?',
            durationHint: 'Speak for 90 seconds.',
            speakText: 'Today I ate soup and toast. My favorite food is pasta. My favorite color is blue.',
          },
        ],
      },
      {
        id: 'unit-1-lesson-3',
        title: 'Lesson 3 — Calm Conversations',
        goal: 'Use breathing before speaking.',
        description: 'Practice soft voice starts, calm repetition, and short conversation flow.',
        durationMins: 12,
        reflectionPrompt: 'How did breathing before speech change the way you spoke today?',
        exercises: [
          {
            id: 'u1-l3-1',
            title: 'Speak on Exhale',
            kind: 'breathing',
            description: 'Begin your words on a slow exhale to reduce tension.',
            instructions: [
              'Take a deep belly breath.',
              'Exhale slowly.',
              'While exhaling, say: Ahhhhhhhhh.',
              'Then say: Hello.',
            ],
            repeatCount: 10,
            speakText: 'Ahhhhhhhhh. Hello.',
          },
          {
            id: 'u1-l3-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Repeat each sentence slowly and keep your jaw loose.',
            phrases: ['Today is a good day.', 'I enjoy talking with people.', 'I take my time when I speak.', 'My ideas are important.', 'I am becoming more confident every day.'],
            repeatCount: 5,
            speakText: 'Today is a good day. I enjoy talking with people.',
          },
          {
            id: 'u1-l3-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times with gentle pacing.',
            readText: 'Confidence grows with practice. Every conversation is an opportunity to learn. I do not need perfect speech. I only need to communicate. Every small improvement matters.',
            durationHint: 'Read three times',
            speakText: 'Confidence grows with practice. Every conversation is an opportunity to learn.',
          },
          {
            id: 'u1-l3-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Talk about your family for two minutes using a calm pace.',
            prompt: 'Tell me about your family. Take a breath before each sentence, slow down, and smile.',
            durationHint: 'Speak for two minutes.',
            speakText: 'My family is very important to me. We spend time together and support each other.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-2',
    title: 'Unit 2',
    theme: 'Gentle Voice',
    goal: 'Learn to begin speaking with a relaxed voice instead of forcing words out.',
    description: 'Start voice onset gently, keep breathing while speaking, and build confidence through everyday greetings.',
    lessons: [
      {
        id: 'unit-2-lesson-1',
        title: 'Lesson 4 — Starting Your Voice Gently',
        goal: 'Learn how to start speaking with a soft, relaxed voice.',
        description: 'Begin speech gently, keep the breath calm, and reduce tension at word beginnings.',
        durationMins: 12,
        coachTip: 'Many people who stutter try to force words out. Instead of pushing, imagine your voice gently riding on your breath.',
        reflectionPrompt: 'Did beginning your words gently feel easier today? Rate the ease from 1 to 5.',
        exercises: [
          {
            id: 'u2-l1-1',
            title: 'Breathing with Voice',
            kind: 'breathing',
            description: 'Breathe in slowly and let your voice float out with the breath.',
            instructions: [
              'Sit comfortably.',
              'Breathe in through your nose for four seconds.',
              'As you breathe out, gently say: Ahhhhhhhhh.',
              'Imagine your voice floating out with your breath.',
              'Do not push your voice.',
            ],
            repeatCount: 10,
            speakText: 'Ahhhhhhhhh',
          },
          {
            id: 'u2-l1-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Start each word softly and linger on the first sound.',
            phrases: ['Hello', 'Apple', 'Open', 'Always', 'Everyone', 'Amazing', 'Afternoon', 'Orange', 'Easy', 'Okay'],
            repeatCount: 5,
            speakText: 'Hello. Apple. Open. Always. Everyone. Amazing. Afternoon. Orange. Easy. Okay.',
          },
          {
            id: 'u2-l1-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times with calm breathing before every sentence.',
            readText: 'Every morning brings a new opportunity. I begin my day with calm breathing and a relaxed voice. I do not rush my words. Speaking gently helps me communicate with confidence and ease.',
            durationHint: 'Read three times. Take one gentle breath before every sentence.',
            speakText: 'Every morning brings a new opportunity. I begin my day with calm breathing and a relaxed voice.',
          },
          {
            id: 'u2-l1-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Answer the questions aloud with a relaxed breath before each answer.',
            prompt: 'What is your name? Where are you from? What do you enjoy doing?',
            durationHint: 'Speak for 90 seconds.',
            speakText: 'My name is Daniel. I am from a calm city. I enjoy walking and reading.',
          },
        ],
      },
      {
        id: 'unit-2-lesson-2',
        title: 'Lesson 5 — Everyday Greetings',
        goal: 'Practice using gentle voice onset during common greetings.',
        description: 'Use calm breathing and soft beginnings to make everyday greetings feel easier.',
        durationMins: 12,
        coachTip: 'A calm breath before a greeting helps your voice begin softly. Focus on relaxed starts more than perfect words.',
        reflectionPrompt: 'Which greeting felt the easiest to say today?',
        exercises: [
          {
            id: 'u2-l2-1',
            title: 'Calm Breathing',
            kind: 'breathing',
            description: 'Count slowly as you breathe out to keep your voice steady.',
            instructions: ['Breathe in for four seconds.', 'Breathe out while counting slowly: One, Two, Three, Four, Five.'],
            repeatCount: 10,
            speakText: 'Breathe in slowly. Breathe out with a calm count.',
          },
          {
            id: 'u2-l2-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Say each greeting with a soft beginning before the sentence.',
            phrases: ['Good morning.', 'Good afternoon.', 'Good evening.', 'Nice to meet you.', 'How are you today?', "It's great to see you.", 'Thank you very much.', 'Have a wonderful day.', 'Welcome.', 'See you later.'],
            repeatCount: 5,
            speakText: 'Good morning. Good afternoon. Good evening. Nice to meet you. How are you today? It is great to see you.',
          },
          {
            id: 'u2-l2-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the greeting passage three times and imagine greeting a real person.',
            readText: 'Greetings are often the first words we speak each day. A calm breath before speaking allows our voice to begin gently. Every greeting is an opportunity to practice relaxed communication.',
            durationHint: 'Read three times. Imagine greeting a real person.',
            speakText: 'Greetings are often the first words we speak each day. A calm breath before speaking allows our voice to begin gently.',
          },
          {
            id: 'u2-l2-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Answer as if meeting a new colleague, using calm breathing and gentle starts.',
            prompt: 'What is your name? What do you do? What are your hobbies?',
            durationHint: 'Speak for two minutes. If you get stuck, pause, breathe, and continue naturally.',
            speakText: 'My name is Daniel. I work with people to help them practice confidence. I enjoy reading and walking.',
          },
        ],
      },
      {
        id: 'unit-2-lesson-3',
        title: 'Lesson 6 — Speaking with Confidence',
        goal: 'Combine relaxed breathing, gentle voice onset, and slow speech in one conversation.',
        description: 'Move from warm-up breathing and soft starts into a longer, confident self-introduction.',
        durationMins: 14,
        coachTip: 'Communication is about sharing ideas, not perfect speech. Keep breathing slowly and start words gently.',
        reflectionPrompt: 'Did beginning your sentences gently help you feel more confident today?',
        exercises: [
          {
            id: 'u2-l3-1',
            title: 'Relax, Breathe, Speak',
            kind: 'breathing',
            description: 'Relax your body, breathe deeply, and say the soft phrase slowly.',
            instructions: ['Relax your shoulders.', 'Take one deep belly breath.', 'Smile.', 'Say softly: Hello.', 'Take another breath.', 'Then say: My name is...', 'Complete the sentence using your own name.'],
            repeatCount: 10,
            speakText: 'Hello. My name is Daniel.',
          },
          {
            id: 'u2-l3-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Speak each sentence slowly and gently while keeping your voice calm.',
            phrases: ['I enjoy learning new things.', 'My voice deserves to be heard.', 'I can take my time when I speak.', 'Every conversation helps me improve.', 'Speaking calmly gives me confidence.', 'I am proud of my progress.', 'My ideas are valuable.', 'I communicate with courage every day.', 'I choose calm over rushing.', 'I believe in myself.'],
            repeatCount: 3,
            speakText: 'I enjoy learning new things. My voice deserves to be heard. I can take my time when I speak.',
          },
          {
            id: 'u2-l3-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times with a relaxed speech pace.',
            readText: 'Communication is about sharing ideas, not speaking perfectly. Every conversation helps us grow. When we breathe calmly and begin our voice gently, speaking becomes easier. Progress happens one conversation at a time.',
            durationHint: 'Read three times. Imagine you are giving a short speech to a friend.',
            speakText: 'Communication is about sharing ideas, not speaking perfectly. Every conversation helps us grow.',
          },
          {
            id: 'u2-l3-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Speak for three minutes about yourself with gentle starts and steady pacing.',
            prompt: 'Where did you grow up? What do you enjoy doing? What is one goal you hope to achieve this year? What makes you happy?',
            durationHint: 'Speak for three minutes. Keep talking even if you stutter.',
            speakText: 'I grew up in a quiet town. I enjoy reading and spending time outdoors.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-3',
    title: 'Unit 3',
    theme: 'Smooth Flow',
    goal: 'Learn to keep your voice flowing smoothly from one word to the next instead of stopping and restarting.',
    description: 'Build continuous airflow, smoother transitions between words, and longer connected phrases.',
    lessons: [
      {
        id: 'unit-3-lesson-1',
        title: 'Lesson 7 — Keeping Your Voice Moving',
        goal: 'Learn to keep your voice flowing continuously while speaking.',
        description: 'Practice continuous airflow, connected phrases, and calm reading without stopping at every word.',
        durationMins: 12,
        coachTip: 'Imagine your voice like a river. Let your words flow gently into one another.',
        techniqueReminders: ['🫁 Breathe First', '🌊 Keep Your Voice Flowing', '🐢 Speak at a Comfortable Pace'],
        reflectionPrompt: 'Did your voice feel more connected today?',
        exercises: [
          {
            id: 'u3-l1-1',
            title: 'Continuous Airflow',
            kind: 'breathing',
            description: 'Hold a calm sound on your breath to build smooth, connected speech.',
            instructions: ['Take a slow belly breath.', 'As you breathe out, say: Aaaaaaaaaaaaaaaaa.', 'Hold the sound comfortably for 5 to 8 seconds.', 'Repeat with Mmmmmmmmmmmmm and Ooooooooooooo.'],
            repeatCount: 10,
            speakText: 'Aaaaaaaaaaaaaaaaa',
          },
          {
            id: 'u3-l1-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Say each phrase without stopping between words.',
            phrases: ['Good morning', 'Thank you', 'Nice to meet you', 'How are you', 'I am happy', 'I like reading', 'Today is beautiful', 'I enjoy learning', 'See you tomorrow', 'Have a great day'],
            repeatCount: 5,
            speakText: 'Good morning. Thank you. Nice to meet you. How are you. I am happy. I like reading.',
          },
          {
            id: 'u3-l1-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage and let the words connect naturally.',
            readText: 'Today I went for a walk in the park. The weather was cool and peaceful. I enjoyed watching the birds and listening to the wind. I took my time and enjoyed every moment.',
            durationHint: 'Read three times. Do not pause between every word.',
            speakText: 'Today I went for a walk in the park. The weather was cool and peaceful.',
          },
          {
            id: 'u3-l1-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Talk about your morning routine in smooth, connected phrases.',
            prompt: 'What time did you wake up? What did you eat? How did you prepare for your day?',
            durationHint: 'Speak for two minutes using smooth, connected speech.',
            speakText: 'I woke up early this morning and had breakfast before I started my day.',
          },
        ],
      },
      {
        id: 'unit-3-lesson-2',
        title: 'Lesson 8 — Linking Your Words',
        goal: 'Practice linking words together into natural sounding phrases.',
        description: 'Count aloud, read in one smooth thought, and talk about a favorite place without breaking the flow.',
        durationMins: 12,
        coachTip: 'Do not think about every single word. Think about sharing one complete idea.',
        techniqueReminders: ['🫁 Breathe First', '🌊 Keep Your Voice Flowing', '🐢 Speak at a Comfortable Pace'],
        reflectionPrompt: 'Did thinking in complete ideas feel easier than thinking in single words?',
        exercises: [
          {
            id: 'u3-l2-1',
            title: 'Breath and Flow',
            kind: 'breathing',
            description: 'Count aloud from 1 to 10 in one relaxed breath.',
            instructions: ['Take one deep breath.', 'Count aloud from 1 to 10.', 'Repeat 5 times.', 'Stay relaxed and do not rush.'],
            repeatCount: 5,
            speakText: 'One, two, three, four, five, six, seven, eight, nine, ten.',
          },
          {
            id: 'u3-l2-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Read each sentence as one smooth thought.',
            phrases: ['I enjoy spending time with my family.', 'My favorite hobby is listening to music.', 'I like meeting new people.', 'Every day I learn something new.', 'Speaking calmly helps me communicate better.', 'I enjoy walking in the evening.', 'My favorite season is the rainy season.', 'I am proud of my progress.', 'I enjoy helping other people.', 'I look forward to tomorrow.'],
            repeatCount: 3,
            speakText: 'I enjoy spending time with my family. My favorite hobby is listening to music.',
          },
          {
            id: 'u3-l2-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the paragraph slowly, naturally, and with expression.',
            readText: 'Every journey begins with a single step. Learning to speak more comfortably takes patience and practice. Small improvements each day become big achievements over time. I celebrate every success, no matter how small.',
            durationHint: 'Read once slowly, once naturally, and once with expression.',
            speakText: 'Every journey begins with a single step. Learning to speak more comfortably takes patience and practice.',
          },
          {
            id: 'u3-l2-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Describe your favorite place in a smooth, natural way.',
            prompt: 'Where is it? Why do you like it? What do you usually do there? Who do you visit it with?',
            durationHint: 'Speak for three minutes.',
            speakText: 'My favorite place is a quiet park near my home because it helps me feel calm and relaxed.',
          },
        ],
      },
      {
        id: 'unit-3-lesson-3',
        title: 'Lesson 9 — Speaking in Longer Sentences',
        goal: 'Use continuous speech while talking for longer periods.',
        description: 'Practice long-breath control, longer sentences, and smooth conversation about a memorable experience.',
        durationMins: 14,
        coachTip: 'If you stutter, pause, breathe, and continue. The goal is to keep communicating.',
        techniqueReminders: ['🫁 Breathe First', '🌊 Keep Your Voice Flowing', '🐢 Speak at a Comfortable Pace'],
        reflectionPrompt: 'How did it feel to keep going after a hard moment?',
        exercises: [
          {
            id: 'u3-l3-1',
            title: 'Long Breath Control',
            kind: 'breathing',
            description: 'Read one sentence in one comfortable breath and repeat it calmly.',
            instructions: ['Take a slow belly breath.', 'Read this sentence in one comfortable breath.', 'Repeat 10 times.', 'If you need another breath, take it calmly and continue.'],
            repeatCount: 10,
            speakText: 'Today I feel relaxed and ready to communicate with confidence.',
          },
          {
            id: 'u3-l3-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Repeat each sentence three times with smooth flow.',
            phrases: ['I enjoy spending weekends with my family and friends.', 'Learning new skills makes me feel confident.', 'Every conversation helps me become a stronger communicator.', 'I speak at a comfortable pace because my ideas are important.', 'My voice deserves time and attention.', 'I enjoy sharing stories with people I care about.', 'Every day brings a new opportunity to practice.', 'Speaking is easier when I stay calm.', 'I communicate with confidence and patience.', 'I believe in my ability to improve.'],
            repeatCount: 3,
            speakText: 'I enjoy spending weekends with my family and friends. Learning new skills makes me feel confident.',
          },
          {
            id: 'u3-l3-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times and imagine you are telling the story to a close friend.',
            readText: 'Last weekend I visited a beautiful garden filled with colorful flowers and tall trees. Children were playing, families were having picnics, and birds were singing. The peaceful environment reminded me that slowing down allows us to enjoy life and communicate more comfortably.',
            durationHint: 'Read three times. On the third reading, imagine you are telling this story to a close friend.',
            speakText: 'Last weekend I visited a beautiful garden filled with colorful flowers and tall trees.',
          },
          {
            id: 'u3-l3-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Speak for four minutes about a memorable experience without memorizing every word.',
            prompt: 'Talk about a birthday celebration, your first day at school, a holiday, a family gathering, or a trip you enjoyed.',
            durationHint: 'Speak for four minutes. If you stutter, pause, breathe, and continue.',
            speakText: 'One memorable experience for me was a family holiday when everyone gathered and shared stories together.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-4',
    title: 'Unit 4',
    theme: 'Easy Articulation',
    goal: 'Learn to produce speech sounds with light, relaxed movements instead of forceful contacts.',
    description: 'Practice relaxed lip contact, gentle tongue movement, reduced tension, and longer comfortable speech.',
    lessons: [
      {
        id: 'unit-4-lesson-1',
        title: 'Lesson 10 — Relax Your Lips',
        goal: 'Learn to pronounce lip sounds gently.',
        description: 'Practice relaxed lip movements, gentle breathing, and soft P and B sounds.',
        durationMins: 12,
        coachTip: 'Your lips only need to touch gently to produce sounds like P and B. More pressure does not produce better speech.',
        techniqueReminders: ['👄 Relax Your Lips', '🫁 Breathe First', '🐢 Speak at a Comfortable Pace'],
        reflectionPrompt: 'Did your lip sounds feel more relaxed today?',
        exercises: [
          {
            id: 'u4-l1-1',
            title: 'Relax and Breathe',
            kind: 'breathing',
            description: 'Gently blow air through relaxed lips as if cooling a cup of tea.',
            instructions: ['Take a slow belly breath.', 'As you breathe out, gently blow air through relaxed lips.', 'Imagine you are cooling a cup of tea.', 'Repeat 10 times.'],
            repeatCount: 10,
            speakText: 'Pfffff. Brrrrr.',
          },
          {
            id: 'u4-l1-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Say each word using very light lip movements.',
            phrases: ['Baby', 'Paper', 'Puppy', 'People', 'Beautiful', 'Peanut', 'Purple', 'Birthday', 'Banana', 'Bicycle'],
            repeatCount: 5,
            speakText: 'Baby. Paper. Puppy. People. Beautiful. Peanut. Purple. Birthday. Banana. Bicycle.',
          },
          {
            id: 'u4-l1-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage with a soft focus on P and B sounds.',
            readText: 'Peter bought a basket of bananas before going to the park. He greeted his friends with a smile and enjoyed spending the afternoon outdoors. Speaking calmly helped him enjoy the conversation.',
            durationHint: 'Read three times. Focus on soft P and B sounds.',
            speakText: 'Peter bought a basket of bananas before going to the park.',
          },
          {
            id: 'u4-l1-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Talk about your favorite meal with relaxed lip movement.',
            prompt: 'What is your favorite meal? Who prepares it? Why do you enjoy it? When do you usually eat it?',
            durationHint: 'Speak for two minutes and pay attention to relaxed lip movement.',
            speakText: 'My favorite meal is soup and bread because it feels comforting and simple.',
          },
        ],
      },
      {
        id: 'unit-4-lesson-2',
        title: 'Lesson 11 — Relax Your Tongue',
        goal: 'Reduce tension when producing tongue sounds.',
        description: 'Practice gentle tongue placement, light T and D sounds, and a relaxed jaw.',
        durationMins: 12,
        coachTip: 'Your tongue should move gently, not forcefully. Let the sound happen instead of making it happen.',
        techniqueReminders: ['👅 Relax Your Tongue', '🫁 Breathe First', '🐢 Speak at a Comfortable Pace'],
        reflectionPrompt: 'Did your tongue feel less tense today?',
        exercises: [
          {
            id: 'u4-l2-1',
            title: 'Tongue Relaxation',
            kind: 'breathing',
            description: 'Place the tongue comfortably behind the bottom teeth and relax the jaw.',
            instructions: ['Take a deep breath.', 'Place your tongue comfortably behind your bottom teeth.', 'Relax your jaw.', 'Repeat 10 times.'],
            repeatCount: 10,
            speakText: 'Tongue relaxed. Jaw relaxed. Voice easy.',
          },
          {
            id: 'u4-l2-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Use light tongue movement in each word.',
            phrases: ['Today', 'Tomorrow', 'Together', 'Different', 'Teacher', 'Dinner', 'Time', 'Table', 'Travel', 'Dream'],
            repeatCount: 5,
            speakText: 'Today. Tomorrow. Together. Different. Teacher. Dinner. Time. Table. Travel. Dream.',
          },
          {
            id: 'u4-l2-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage with gentle T and D sounds.',
            readText: 'Today my teacher talked about teamwork. Everyone shared ideas and listened carefully. Working together made the project enjoyable and successful.',
            durationHint: 'Read three times. Focus on gentle T and D sounds.',
            speakText: 'Today my teacher talked about teamwork. Everyone shared ideas and listened carefully.',
          },
          {
            id: 'u4-l2-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Describe your typical day with relaxed tongue movement.',
            prompt: 'What happens in the morning? What happens in the afternoon? What happens in the evening?',
            durationHint: 'Speak for three minutes and stay relaxed.',
            speakText: 'In the morning I wake up and get ready for the day. In the afternoon I usually work or study. In the evening I relax.',
          },
        ],
      },
      {
        id: 'unit-4-lesson-3',
        title: 'Lesson 12 — Speaking Comfortably',
        goal: 'Combine relaxed breathing, gentle voice onset, continuous speech, and light articulation.',
        description: 'Practice a four-step routine and speak for longer with relaxed movement.',
        durationMins: 14,
        coachTip: 'Use all the techniques you have learned so far. A calm routine makes speech feel easier.',
        techniqueReminders: ['🫁 Breathe First', '🌊 Keep Your Voice Flowing', '👄 Relax Your Lips', '👅 Relax Your Tongue'],
        reflectionPrompt: 'How did combining the techniques change the way speaking felt?',
        exercises: [
          {
            id: 'u4-l3-1',
            title: 'The Four Step Routine',
            kind: 'breathing',
            description: 'Before every sentence, relax, breathe, begin gently, and speak lightly.',
            instructions: ['Relax your shoulders.', 'Take one belly breath.', 'Begin gently.', 'Speak with light movements.'],
            repeatCount: 10,
            speakText: 'Relax. Breathe. Begin gently. Speak lightly.',
          },
          {
            id: 'u4-l3-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Repeat each sentence three times with light articulation.',
            phrases: ['My family enjoys spending time together every weekend.', 'Today I learned something new that made me smile.', 'I enjoy helping people whenever I can.', 'Every conversation gives me another chance to grow.', 'Speaking calmly feels more comfortable every day.', 'I take my time because my ideas matter.', 'Confidence grows through practice.', 'I am becoming a better communicator.', 'My speech does not define me.', 'I am proud of the effort I make each day.'],
            repeatCount: 3,
            speakText: 'My family enjoys spending time together every weekend. Today I learned something new that made me smile.',
          },
          {
            id: 'u4-l3-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times and then read it to a friend.',
            readText: 'Good communication is about expressing ideas clearly and confidently. Every conversation is an opportunity to connect with others. By breathing calmly, speaking gently, and relaxing our speech muscles, we can communicate more comfortably.',
            durationHint: 'Read three times. Read the final version as if you are speaking to a friend.',
            speakText: 'Good communication is about expressing ideas clearly and confidently. Every conversation is an opportunity to connect with others.',
          },
          {
            id: 'u4-l3-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Speak for four minutes about a person you admire using all the techniques you have learned so far.',
            prompt: 'Who are they? Why do you admire them? What have you learned from them? How do they inspire you?',
            durationHint: 'Speak for four minutes. Pause if needed, then continue.',
            speakText: 'I admire my grandmother because she has always shown kindness, patience, and strength.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-5',
    title: 'Unit 5',
    theme: 'Everyday Conversations',
    goal: 'Learn to use your fluency techniques during everyday conversations and connect with people confidently.',
    description: 'Practice starting conversations, asking for help, and staying engaged in real-world interactions.',
    lessons: [
      {
        id: 'unit-5-lesson-1',
        title: 'Lesson 13 — Starting Everyday Conversations',
        goal: 'Learn to start simple conversations with confidence.',
        description: 'Prepare before speaking, greet others naturally, and begin with calm confidence.',
        durationMins: 12,
        coachTip: 'People remember your friendliness far more than your fluency.',
        techniqueReminders: ['☕ Start Gently', '🫁 Breathe First', '👀 Keep Eye Contact'],
        reflectionPrompt: 'Did starting with a calm routine make conversation feel easier?',
        exercises: [
          {
            id: 'u5-l1-1',
            title: 'Prepare Before Speaking',
            kind: 'breathing',
            description: 'Use a short routine before a conversation: relax, breathe, smile, and begin gently.',
            instructions: ['Relax your shoulders.', 'Take one slow belly breath.', 'Smile.', 'Think about your message.', 'Begin speaking gently.'],
            repeatCount: 10,
            speakText: 'Relax. Breathe. Smile. Begin gently.',
          },
          {
            id: 'u5-l1-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Imagine speaking to a cashier and say each phrase naturally.',
            phrases: ['Hello.', 'Good morning.', 'How are you today?', 'Thank you.', 'Have a wonderful day.', 'I appreciate your help.', 'Excuse me.', 'You are welcome.', 'That is perfect.', 'See you again.'],
            repeatCount: 5,
            speakText: 'Hello. Good morning. How are you today? Thank you. Have a wonderful day.',
          },
          {
            id: 'u5-l1-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage as if you are speaking directly to another person.',
            readText: 'Every conversation begins with a single word. I do not need to rush. I take a breath, begin gently, and share my thoughts one sentence at a time. My goal is to connect with people, not to speak perfectly.',
            durationHint: 'Read three times. Imagine you are speaking directly to another person.',
            speakText: 'Every conversation begins with a single word. I do not need to rush. I take a breath, begin gently.',
          },
          {
            id: 'u5-l1-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Act out a coffee shop interaction and continue naturally for two minutes.',
            prompt: 'You are buying coffee. Speak as both yourself and the cashier. Start with a greeting and continue naturally.',
            durationHint: 'Continue naturally for two minutes.',
            speakText: 'Good morning. I would like a cup of coffee, please. No, thank you. That will be all.',
          },
        ],
      },
      {
        id: 'unit-5-lesson-2',
        title: 'Lesson 14 — Asking for Help',
        goal: 'Practice speaking when asking questions.',
        description: 'Use calm breathing, clear questions, and confident follow-up in everyday situations.',
        durationMins: 12,
        coachTip: 'Curiosity is stronger than fear. Focus on getting information, not on speaking perfectly.',
        techniqueReminders: ['❓ Ask Clearly', '🫁 Breathe First', '🌱 Stay Calm'],
        reflectionPrompt: 'Did asking for help feel easier when you focused on the purpose of the conversation?',
        exercises: [
          {
            id: 'u5-l2-1',
            title: 'Reset Breath',
            kind: 'breathing',
            description: 'Take one deep breath, exhale slowly, and remind yourself that you have time.',
            instructions: ['Take one deep breath.', 'Exhale slowly.', 'Say: I have time.'],
            repeatCount: 10,
            speakText: 'I have time.',
          },
          {
            id: 'u5-l2-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Repeat each sentence naturally and with calm confidence.',
            phrases: ['Excuse me, could you help me?', 'Where is the nearest bank?', 'Which bus goes downtown?', 'How much does this cost?', 'Could you repeat that?', 'Thank you for your help.', 'I understand.', 'That makes sense.', 'I appreciate it.', 'Have a nice day.'],
            repeatCount: 5,
            speakText: 'Excuse me, could you help me? Where is the nearest bank? Which bus goes downtown?',
          },
          {
            id: 'u5-l2-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage and remember that asking questions is a normal part of life.',
            readText: 'Asking questions is a normal part of everyday life. Everyone needs help sometimes. I take a calm breath before asking my question, and I allow myself enough time to finish speaking.',
            durationHint: 'Read three times.',
            speakText: 'Asking questions is a normal part of everyday life. Everyone needs help sometimes.',
          },
          {
            id: 'u5-l2-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Imagine you are inside a supermarket and ask an employee for help finding three items.',
            prompt: 'Ask for help finding three different items and continue the conversation naturally.',
            durationHint: 'Speak for three minutes.',
            speakText: 'Excuse me, could you help me find the pasta and the cereal? Thank you for your help.',
          },
        ],
      },
      {
        id: 'unit-5-lesson-3',
        title: 'Lesson 15 — Real Conversations',
        goal: 'Use all the fluency skills you have learned in a natural conversation.',
        description: 'Relax, breathe, begin gently, and keep talking even if the conversation gets difficult.',
        durationMins: 14,
        coachTip: 'Great conversations are built on listening, sharing, and connecting. Fluency is only one part of communication.',
        techniqueReminders: ['💬 Stay Engaged', '🫁 Breathe First', '🌱 Keep Going'],
        reflectionPrompt: 'How did it feel to stay engaged instead of chasing perfection?',
        exercises: [
          {
            id: 'u5-l3-1',
            title: 'The Conversation Reset',
            kind: 'breathing',
            description: 'When tension appears, relax, breathe, begin gently, and keep talking.',
            instructions: ['Relax.', 'Breathe.', 'Begin gently.', 'Keep talking.'],
            repeatCount: 10,
            speakText: 'Relax. Breathe. Begin gently. Keep talking.',
          },
          {
            id: 'u5-l3-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Repeat each sentence naturally and warmly.',
            phrases: ['It is nice to finally meet you.', 'Tell me more about yourself.', 'That sounds interesting.', 'I completely understand.', 'What do you enjoy doing?', 'I would love to hear your opinion.', 'Thank you for sharing.', 'That is a great idea.', 'I learned something new today.', 'It was wonderful talking with you.'],
            repeatCount: 3,
            speakText: 'It is nice to finally meet you. Tell me more about yourself. That sounds interesting.',
          },
          {
            id: 'u5-l3-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times and imagine you are giving advice to a friend.',
            readText: 'Great conversations are built on listening, sharing, and connecting. Fluency is only one part of communication. Confidence, kindness, and curiosity are just as important. Every conversation is an opportunity to build meaningful relationships.',
            durationHint: 'Read three times. On your final reading, imagine you are giving advice to a friend.',
            speakText: 'Great conversations are built on listening, sharing, and connecting. Fluency is only one part of communication.',
          },
          {
            id: 'u5-l3-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Speak for five minutes about your ideal weekend and stay engaged even if your thoughts wander.',
            prompt: 'Describe your ideal weekend. Include where you would go, who you would spend time with, what activities you would enjoy, and why it would make you happy.',
            durationHint: 'Pause, breathe, and continue if you lose your train of thought.',
            speakText: 'My ideal weekend would be spent in a quiet place with friends, enjoying good food and long conversations.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-6',
    title: 'Unit 6',
    theme: 'Confident Phone Calls',
    goal: 'Develop confidence and fluency during phone conversations by preparing before speaking, maintaining relaxed speech, and responding naturally.',
    description: 'Practice preparing for calls, asking and answering questions over the phone, and staying calm during real conversations.',
    lessons: [
      {
        id: 'unit-6-lesson-1',
        title: 'Lesson 16 — Preparing for a Phone Call',
        goal: 'Learn how to prepare your body and mind before making or answering a phone call.',
        description: 'Use a short phone reset routine and practice calm opening phrases.',
        durationMins: 12,
        coachTip: 'Silence during a phone call is normal. You do not have to fill every second with words.',
        techniqueReminders: ['☎️ Prepare Before You Call', '🫁 Breathe First', '🌿 Stay Relaxed'],
        reflectionPrompt: 'Did the reset routine help you feel more settled before speaking?',
        exercises: [
          {
            id: 'u6-l1-1',
            title: 'The Phone Reset',
            kind: 'breathing',
            description: 'Before every practice call, sit comfortably, relax, breathe, and begin gently.',
            instructions: ['Sit comfortably.', 'Relax your shoulders.', 'Take one slow belly breath.', 'Exhale slowly.', 'Smile.', 'Begin speaking gently.'],
            repeatCount: 10,
            speakText: 'Relax. Breathe. Smile. Begin gently.',
          },
          {
            id: 'u6-l1-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Imagine you are calling a business and practice the opening phrases.',
            phrases: ['Hello.', 'Good morning.', 'My name is _____.', 'I would like some information.', 'Could you please help me?', 'Thank you for your time.', 'Have a wonderful day.', 'Goodbye.', 'I appreciate your help.', "I'll call again if needed."],
            repeatCount: 5,
            speakText: 'Hello. Good morning. My name is Daniel. I would like some information. Could you please help me?',
          },
          {
            id: 'u6-l1-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage as if you are speaking to a real person on the phone.',
            readText: 'Phone conversations can feel challenging because we cannot see the other person’s face. Taking one calm breath before speaking helps us stay relaxed. I do not need to hurry. I have enough time to express my thoughts clearly.',
            durationHint: 'Read three times. Imagine you are speaking to a real person on the phone.',
            speakText: 'Phone conversations can feel challenging because we cannot see the other person’s face. Taking one calm breath before speaking helps us stay relaxed.',
          },
          {
            id: 'u6-l1-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Pretend you are calling a restaurant and ask a few questions.',
            prompt: 'Are you open today? What time do you close? Do you have vegetarian meals? Thank you for your help.',
            durationHint: 'Speak for two minutes.',
            speakText: 'Hello, are you open today? What time do you close? Do you have vegetarian meals? Thank you for your help.',
          },
        ],
      },
      {
        id: 'unit-6-lesson-2',
        title: 'Lesson 17 — Asking Questions on the Phone',
        goal: 'Practice asking questions naturally during a phone conversation.',
        description: 'Use calm counting, clear questions, and steady pacing during phone-based requests.',
        durationMins: 12,
        coachTip: 'If you stutter during a phone call, keep going. Most people are focused on helping you, not judging your speech.',
        techniqueReminders: ['📞 Ask Clearly', '🫁 Breathe First', '🐢 Speak at a Comfortable Pace'],
        reflectionPrompt: 'Did slower, clearer questions feel easier on the phone?',
        exercises: [
          {
            id: 'u6-l2-1',
            title: 'Calm Counting',
            kind: 'breathing',
            description: 'Take a belly breath, count slowly from 1 to 10, and stay relaxed.',
            instructions: ['Take a belly breath.', 'Count slowly from 1 to 10.', 'Repeat 5 times.'],
            repeatCount: 5,
            speakText: 'One, two, three, four, five, six, seven, eight, nine, ten.',
          },
          {
            id: 'u6-l2-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Repeat each sentence calmly and naturally.',
            phrases: ["I'd like to make an appointment.", 'Could you repeat that, please?', 'What time is available?', 'Can I speak with the manager?', 'Thank you for your patience.', 'That works for me.', "I'll see you then.", 'Have a great day.', 'I understand.', 'Thank you very much.'],
            repeatCount: 5,
            speakText: 'I would like to make an appointment. Could you repeat that, please? What time is available?',
          },
          {
            id: 'u6-l2-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage and remember that clarity matters more than speed.',
            readText: 'Good communication is not about speaking quickly. It is about sharing information clearly. During a phone call, I pause when I need to, breathe calmly, and continue speaking with confidence.',
            durationHint: 'Read three times.',
            speakText: 'Good communication is not about speaking quickly. It is about sharing information clearly.',
          },
          {
            id: 'u6-l2-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Pretend you are calling a doctor’s office and ask for an appointment.',
            prompt: 'I would like to book an appointment. What times are available? What should I bring? Thank you for your assistance.',
            durationHint: 'Continue speaking for three minutes.',
            speakText: 'Hello, I would like to book an appointment. What times are available? What should I bring? Thank you for your assistance.',
          },
        ],
      },
      {
        id: 'unit-6-lesson-3',
        title: 'Lesson 18 — Handling Real Phone Conversations',
        goal: 'Use all your fluency skills during a complete phone conversation.',
        description: 'Practice a four-step call routine and stay engaged in a longer phone exchange.',
        durationMins: 14,
        coachTip: 'Every successful phone call builds confidence. Focus on your message rather than your fluency.',
        techniqueReminders: ['📞 Stay Engaged', '🫁 Breathe First', '🌿 Keep Going'],
        reflectionPrompt: 'How did it feel to stay with the phone conversation even when it felt hard?',
        exercises: [
          {
            id: 'u6-l3-1',
            title: 'The Four Step Call Routine',
            kind: 'breathing',
            description: 'Before speaking, relax, breathe, begin gently, and speak naturally.',
            instructions: ['Relax.', 'Breathe.', 'Begin gently.', 'Speak naturally.'],
            repeatCount: 10,
            speakText: 'Relax. Breathe. Begin gently. Speak naturally.',
          },
          {
            id: 'u6-l3-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Repeat each sentence calmly and clearly.',
            phrases: ['Hello, my name is _____.', "I'm calling because I have a question.", 'Thank you for taking my call.', 'Could you explain that again?', 'I appreciate your patience.', 'That answers my question.', 'Thank you for your help today.', 'Have a wonderful afternoon.', 'Goodbye.', 'I look forward to speaking with you again.'],
            repeatCount: 3,
            speakText: 'Hello, my name is Daniel. I am calling because I have a question. Thank you for taking my call.',
          },
          {
            id: 'u6-l3-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times and imagine you are speaking to a friend.',
            readText: 'Every successful phone call builds confidence. I focus on my message rather than my fluency. I breathe before speaking, communicate one idea at a time, and allow myself to speak at a comfortable pace. My voice deserves to be heard.',
            durationHint: 'Read three times. On your final reading, imagine you are speaking to a friend.',
            speakText: 'Every successful phone call builds confidence. I focus on my message rather than my fluency.',
          },
          {
            id: 'u6-l3-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Role play a five minute phone conversation about a course you would like to join.',
            prompt: 'Discuss course details, fees, start date, duration, and the registration process.',
            durationHint: 'Stay engaged even if you experience moments of stuttering.',
            speakText: 'Hello, I am calling to ask about the course you offer. Could you tell me about the fees and the start date?',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-8',
    title: 'Unit 8',
    theme: 'Workplace & Job Interviews',
    goal: 'Build the confidence and communication skills needed for interviews, meetings, networking, and professional conversations.',
    description: 'Practice introducing yourself professionally, answering interview questions thoughtfully, and speaking with confidence in workplace conversations.',
    lessons: [
      {
        id: 'unit-8-lesson-1',
        title: 'Lesson 22 — Introducing Yourself Professionally',
        goal: 'Learn to introduce yourself with confidence in a professional setting.',
        description: 'Practice a calm, confident introduction that feels clear, honest, and natural.',
        durationMins: 12,
        coachTip: 'Interviewers remember confidence, preparation, and authenticity far more than perfect fluency.',
        techniqueReminders: ['💼 Be Clear', '🫁 Breathe First', '🌟 Share Your Strengths'],
        reflectionPrompt: 'Did your professional introduction feel clear and comfortable today?',
        exercises: [
          {
            id: 'u8-l1-1',
            title: 'Confidence Breath',
            kind: 'breathing',
            description: 'Before speaking, relax your body and connect with one strength you bring.',
            instructions: ['Sit comfortably.', 'Relax your shoulders.', 'Take a slow belly breath.', 'Smile.', 'Think about one thing you are proud of.'],
            repeatCount: 10,
            speakText: 'I am proud of the way I keep learning and growing.',
          },
          {
            id: 'u8-l1-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Practice natural, professional self-introductions with calm pacing.',
            phrases: ['Good morning. My name is _____.', "It's a pleasure to meet you.", 'Thank you for this opportunity.', 'I recently graduated from university.', 'I enjoy solving problems.', 'I work well with others.', "I'm excited to learn new skills.", 'I believe I can contribute to your team.', 'Thank you for your time.', 'I look forward to hearing from you.'],
            repeatCount: 3,
            speakText: 'Good morning. My name is Daniel. I enjoy solving problems. I work well with others.',
          },
          {
            id: 'u8-l1-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the paragraph three times and focus on sounding warm and clear.',
            readText: 'A professional introduction does not have to be perfect. It should be honest, confident, and clear. I focus on sharing who I am rather than worrying about every word. My experience and ideas are valuable.',
            durationHint: 'Read three times.',
            speakText: 'A professional introduction does not have to be perfect. It should be honest, confident, and clear.',
          },
          {
            id: 'u8-l1-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Imagine you have just entered an interview room and introduce yourself.',
            prompt: 'Include your name, where you are from, your education, your interests, and one strength you bring. Speak for three minutes.',
            durationHint: 'Speak for three minutes.',
            speakText: 'Hello, my name is Daniel. I am from a small town. I recently graduated from university and I enjoy solving problems and working with others.',
          },
        ],
      },
      {
        id: 'unit-8-lesson-2',
        title: 'Lesson 23 — Answering Interview Questions',
        goal: 'Practice responding thoughtfully without rushing.',
        description: 'Learn to pause, organize your answer, and speak calmly under pressure.',
        durationMins: 12,
        coachTip: 'A thoughtful pause often makes you sound more confident. Silence is not your enemy.',
        techniqueReminders: ['🧠 Pause Before You Answer', '🫁 Breathe First', '✨ Share Your Ideas Clearly'],
        reflectionPrompt: 'Did pausing before you answered make you feel more composed?',
        exercises: [
          {
            id: 'u8-l2-1',
            title: 'Pause Before You Answer',
            kind: 'breathing',
            description: 'Take a breath, wait two seconds, and then answer thoughtfully.',
            instructions: ['Take a breath.', 'Wait for two seconds.', 'Then answer.', 'Repeat ten times.'],
            repeatCount: 10,
            speakText: 'I need a moment to think about that. I will answer carefully.',
          },
          {
            id: 'u8-l2-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Practice calm, thoughtful interview language.',
            phrases: ['Thank you for your question.', 'Let me think about that.', 'One example is...', 'I learned a lot from that experience.', 'I enjoy working with people.', 'I like solving challenges.', 'I always try to improve.', 'That experience taught me resilience.', 'I appreciate constructive feedback.', "I'm excited about this opportunity."],
            repeatCount: 3,
            speakText: 'Thank you for your question. Let me think about that. One example is this.',
          },
          {
            id: 'u8-l2-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times and let your answers feel calm and organized.',
            readText: 'Every interview is a conversation. I listen carefully before answering. I take my time to organize my thoughts. Speaking calmly allows my ideas to come through clearly.',
            durationHint: 'Read three times.',
            speakText: 'Every interview is a conversation. I listen carefully before answering.',
          },
          {
            id: 'u8-l2-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Answer common interview questions aloud with calm pacing.',
            prompt: 'Tell me about yourself. Why do you want this job? What are your strengths? Tell me about a challenge you overcame. Where do you see yourself in five years? Speak for five minutes.',
            durationHint: 'Speak for five minutes.',
            speakText: 'I am someone who enjoys learning. I am motivated by solving problems and working with others.',
          },
        ],
      },
      {
        id: 'unit-8-lesson-3',
        title: 'Lesson 24 — Professional Conversations',
        goal: 'Use your fluency skills during workplace conversations.',
        description: 'Practice contributing ideas, responding in meetings, and staying composed during important professional moments.',
        durationMins: 14,
        coachTip: 'Meetings are opportunities to contribute ideas and collaborate with others. You do not need perfect speech to make valuable contributions.',
        techniqueReminders: ['🤝 Share Your Ideas', '🫁 Breathe First', '🌿 Stay Composed'],
        reflectionPrompt: 'How did it feel to contribute ideas while staying calm and present?',
        exercises: [
          {
            id: 'u8-l3-1',
            title: 'Meeting Reset',
            kind: 'breathing',
            description: 'Before speaking in a meeting, relax, breathe, organize your first sentence, and begin gently.',
            instructions: ['Relax.', 'Breathe.', 'Organize your first sentence.', 'Begin gently.'],
            repeatCount: 10,
            speakText: 'Relax. Breathe. Begin gently. Share your idea.',
          },
          {
            id: 'u8-l3-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Practice professional phrases that help you contribute clearly in work or study settings.',
            phrases: ['I have an idea I would like to share.', 'I agree with that suggestion.', 'Could you explain that again?', 'Thank you for your feedback.', 'I think we should consider another option.', "That's an excellent point.", "I'd like to add something.", "I appreciate everyone's contribution.", "Let's work together on this.", 'Thank you for listening.'],
            repeatCount: 3,
            speakText: 'I have an idea I would like to share. Thank you for your feedback.',
          },
          {
            id: 'u8-l3-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the paragraph three times and imagine speaking up in a team meeting.',
            readText: 'Meetings are opportunities to contribute ideas and collaborate with others. I do not need perfect speech to make valuable contributions. I prepare my thoughts, breathe calmly, and speak with confidence.',
            durationHint: 'Read three times.',
            speakText: 'Meetings are opportunities to contribute ideas and collaborate with others. I do not need perfect speech to make valuable contributions.',
          },
          {
            id: 'u8-l3-4',
            title: 'Conversation Challenge',
            kind: 'conversation',
            description: 'Imagine you are in a team meeting and present an idea for improving your workplace or university.',
            prompt: 'Include the problem, your proposed solution, why it would help, and how it could be implemented. Speak for five minutes.',
            durationHint: 'Speak for five minutes.',
            speakText: 'I would like to suggest a small change that could make our workplace more efficient and friendly.',
          },
        ],
      },
    ],
  },
  {
    id: 'unit-9',
    title: 'Unit 9',
    theme: 'Public Speaking & Presentations',
    goal: 'Develop the confidence to speak in front of an audience using all the fluency shaping skills learned throughout the course.',
    description: 'Practice preparing for presentations, organizing a clear message, and speaking with confidence in front of others.',
    lessons: [
      {
        id: 'unit-9-lesson-1',
        title: 'Lesson 25 — Preparing to Speak',
        goal: 'Learn how to prepare your body and mind before speaking to a group.',
        description: 'Practice a presentation reset routine and build comfort speaking in front of an audience.',
        durationMins: 12,
        coachTip: 'Your audience is listening for your ideas, not counting your moments of stuttering.',
        techniqueReminders: ['🎤 Prepare Before You Speak', '🫁 Breathe First', '🌟 Smile and Connect'],
        reflectionPrompt: 'Did the presentation reset help you feel more settled before speaking?',
        exercises: [
          {
            id: 'u9-l1-1',
            title: 'Presentation Reset',
            kind: 'breathing',
            description: 'Stand comfortably, relax your shoulders, take a slow breath, and imagine speaking successfully.',
            instructions: ['Stand with both feet comfortably on the floor.', 'Relax your shoulders.', 'Take a slow belly breath.', 'Exhale gently.', 'Smile.', 'Visualize yourself speaking successfully.'],
            repeatCount: 10,
            speakText: 'I am ready to speak. I have something valuable to say.',
          },
          {
            id: 'u9-l1-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Practice audience-friendly opening phrases as if a group is in front of you.',
            phrases: ['Good morning everyone.', 'Thank you for being here.', "Today I'd like to share an important idea.", "Let's begin.", "First, I'd like to explain...", "Now let's look at...", 'Finally...', 'Thank you for listening.', 'I appreciate your attention.', 'Have a wonderful day.'],
            repeatCount: 3,
            speakText: 'Good morning everyone. Thank you for being here. Today I would like to share an important idea.',
          },
          {
            id: 'u9-l1-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times, then read it one final time standing up.',
            readText: 'Speaking in front of others can feel intimidating, but preparation builds confidence. I do not need to eliminate every moment of stuttering. My audience wants to understand my message, and I deserve the opportunity to share it.',
            durationHint: 'Read three times. Read the final version standing up.',
            speakText: 'Speaking in front of others can feel intimidating, but preparation builds confidence.',
          },
          {
            id: 'u9-l1-4',
            title: 'Speaking Challenge',
            kind: 'conversation',
            description: 'Deliver a two-minute presentation about your favorite hobby.',
            prompt: 'Include what it is, how you started, why you enjoy it, and why others might enjoy it too.',
            durationHint: 'Speak for two minutes.',
            speakText: 'My favorite hobby is reading because it gives me calm, comfort, and new ideas.',
          },
        ],
      },
      {
        id: 'unit-9-lesson-2',
        title: 'Lesson 26 — Organizing Your Message',
        goal: 'Learn to structure a presentation so it feels easier to deliver.',
        description: 'Practice organizing thoughts into a beginning, middle, and ending.',
        durationMins: 12,
        coachTip: 'Strong presentations are built on clear ideas, not perfect delivery.',
        techniqueReminders: ['🧭 Start With a Clear Structure', '🫁 Breathe First', '⏸️ Use Pauses Naturally'],
        reflectionPrompt: 'Did organizing your message make the talk feel easier to deliver?',
        exercises: [
          {
            id: 'u9-l2-1',
            title: 'Calm Breathing',
            kind: 'breathing',
            description: 'Take ten slow belly breaths and remind yourself that you have something valuable to say.',
            instructions: ['Take ten slow belly breaths.', 'Before each breath, silently think: I have something valuable to say.'],
            repeatCount: 10,
            speakText: 'I have something valuable to say.',
          },
          {
            id: 'u9-l2-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Practice the language of a structured presentation.',
            phrases: ["Today I'd like to talk about...", 'There are three reasons for this.', 'First...', 'Second...', 'Finally...', 'In conclusion...', 'Thank you for listening.', 'I hope you found this useful.', "I'd be happy to answer questions.", 'Thank you.'],
            repeatCount: 3,
            speakText: 'Today I would like to talk about the importance of staying curious. There are three reasons for this.',
          },
          {
            id: 'u9-l2-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times and focus on a clear beginning, middle, and ending.',
            readText: 'A clear presentation has a beginning, a middle, and an ending. Organizing my thoughts before speaking helps me stay focused and reduces pressure. I speak one idea at a time and allow natural pauses between sections.',
            durationHint: 'Read three times.',
            speakText: 'A clear presentation has a beginning, a middle, and an ending. Organizing my thoughts before speaking helps me stay focused.',
          },
          {
            id: 'u9-l2-4',
            title: 'Speaking Challenge',
            kind: 'conversation',
            description: 'Give a four-minute presentation about one problem in your community and how it could be solved.',
            prompt: 'Structure your talk with an introduction, the problem, your solution, and a conclusion.',
            durationHint: 'Speak for four minutes.',
            speakText: 'One problem in my community is that many people feel disconnected from one another. I believe a shared community space could help.',
          },
        ],
      },
      {
        id: 'unit-9-lesson-3',
        title: 'Lesson 27 — Speaking with Confidence',
        goal: 'Deliver a complete presentation while staying calm and engaged with your audience.',
        description: 'Practice a fuller presentation and learn how to stay present while speaking.',
        durationMins: 14,
        coachTip: 'Confidence is not speaking without fear. Confidence is choosing to speak even when fear is present.',
        techniqueReminders: ['🎯 Focus on Your Message', '🫁 Breathe First', '🌟 Stay Connected to Your Audience'],
        reflectionPrompt: 'How did your confidence change while delivering the full presentation?',
        exercises: [
          {
            id: 'u9-l3-1',
            title: 'The Speaker\'s Routine',
            kind: 'breathing',
            description: 'Before speaking, relax, breathe, smile, begin gently, and focus on your audience.',
            instructions: ['Relax.', 'Breathe.', 'Smile.', 'Begin gently.', 'Focus on your audience.'],
            repeatCount: 10,
            speakText: 'Relax. Breathe. Smile. Begin gently. Focus on your audience.',
          },
          {
            id: 'u9-l3-2',
            title: 'Repeat After Me',
            kind: 'repeat',
            description: 'Practice phrases that help you speak clearly and warmly in front of a group.',
            phrases: ["I'd like to share a story.", 'Thank you for this opportunity.', 'This topic is important because...', 'Let me explain.', "Here's an example.", 'I believe we can make a difference.', 'Thank you for your attention.', "I'd be happy to answer your questions.", 'I appreciate your time.', 'Have a wonderful day.'],
            repeatCount: 3,
            speakText: 'I would like to share a story. Thank you for this opportunity. This topic is important because it matters to me.',
          },
          {
            id: 'u9-l3-3',
            title: 'Reading',
            kind: 'reading',
            description: 'Read the passage three times and imagine you are addressing an audience of fifty people.',
            readText: 'Public speaking is not about being perfect. It is about connecting with people. Every great speaker has experienced nervousness. Confidence grows each time I choose to speak despite my fears. My message is worth sharing.',
            durationHint: 'Read three times. Imagine you are addressing an audience of fifty people.',
            speakText: 'Public speaking is not about being perfect. It is about connecting with people.',
          },
          {
            id: 'u9-l3-4',
            title: 'Speaking Challenge',
            kind: 'conversation',
            description: 'Deliver a five-minute presentation about a goal you want to achieve in the next five years.',
            prompt: 'Include what your goal is, why it matters to you, the challenges you may face, the steps you will take, and how achieving it would change your life.',
            durationHint: 'Record your presentation and watch it afterward. Celebrate what you did well before identifying one area to improve.',
            speakText: 'In the next five years, I want to build a meaningful career and continue growing as a person.',
          },
        ],
      },
    ],
  },
  {
    id: "unit-10",
    title: "Unit 10",
    theme: "Fluent Living",
    goal: "Develop lifelong communication habits that support confident speaking in everyday life and beyond the course.",
    description: "A graduation-style finale that helps users transition from structured practice to confident, authentic communication in real life.",
    lessons: [
      {
        id: "unit-10-lesson-1",
        title: "Lesson 28 — Trust Your Skills",
        goal: "Recognize how much you have learned and begin relying on your skills naturally.",
        description: "Center yourself, repeat affirming phrases, and reflect on how confidence has grown.",
        durationMins: 12,
        coachTip: "Confidence is built through thousands of conversations, not one perfect day.",
        techniqueReminders: ["🌱 Trust Your Voice", "🫁 Breathe Before You Speak", "💛 Celebrate Progress"],
        reflectionPrompt: "How has your confidence changed since you started this course?",
        exercises: [
          {
            id: "u10-l1-1",
            title: "Center Yourself",
            kind: "breathing",
            description: "Take ten slow belly breaths and silently repeat that you trust your voice.",
            instructions: ["Close your eyes.", "Take ten slow belly breaths.", "With every exhale silently say: I trust my voice.", "Notice how calm your body feels before speaking."],
            repeatCount: 10,
            speakText: "I trust my voice."
          },
          {
            id: "u10-l1-2",
            title: "Repeat After Me",
            kind: "repeat",
            description: "Practice affirming phrases that support confidence and calm communication.",
            phrases: ["I do not need to rush.", "I trust the skills I have learned.", "Every conversation is an opportunity to connect.", "My voice is valuable.", "I can pause whenever I need to.", "I communicate with confidence.", "Progress matters more than perfection.", "I am proud of my journey.", "I have grown stronger every day.", "My voice deserves to be heard."],
            repeatCount: 3,
            speakText: "I trust the skills I have learned. My voice is valuable."
          },
          {
            id: "u10-l1-3",
            title: "Reading",
            kind: "reading",
            description: "Read the passage three times, then read it one final time as if you are encouraging someone else.",
            readText: "Communication is a lifelong journey. Every conversation teaches us something new. I no longer measure success by perfect fluency. I measure success by my willingness to speak, connect, and express myself with confidence.",
            durationHint: "Read three times.",
            speakText: "Communication is a lifelong journey. Every conversation teaches us something new."
          },
          {
            id: "u10-l1-4",
            title: "Conversation Challenge",
            kind: "conversation",
            description: "Speak for five minutes about how your confidence has changed since you started the course.",
            prompt: "Include what felt difficult at first, what became easier, what you are proud of, and what you want to keep improving.",
            durationHint: "Speak for five minutes.",
            speakText: "At first it felt difficult to speak without pressure, but now I can pause and trust myself more."
          }
        ]
      },
      {
        id: "unit-10-lesson-2",
        title: "Lesson 29 — Communicating Through Challenges",
        goal: "Learn how to respond calmly when communication feels difficult.",
        description: "Practice a reset routine, affirm your ability to continue, and reflect on recent difficult conversations.",
        durationMins: 12,
        coachTip: "A difficult conversation is not a failed conversation. If you shared your thoughts honestly, you succeeded.",
        techniqueReminders: ["🧘 Pause and Reset", "🫁 Breathe Before You Continue", "🌟 Keep Going"],
        reflectionPrompt: "What helped you stay present during a difficult conversation?",
        exercises: [
          {
            id: "u10-l2-1",
            title: "Reset Routine",
            kind: "breathing",
            description: "Whenever tension rises while speaking, pause, relax your shoulders, take one slow breath, and continue.",
            instructions: ["Pause.", "Relax your shoulders.", "Take one slow breath.", "Continue speaking."],
            repeatCount: 10,
            speakText: "Pause. Relax. Breathe. Continue."
          },
          {
            id: "u10-l2-2",
            title: "Repeat After Me",
            kind: "repeat",
            description: "Practice phrases that support calm resilience in hard speaking moments.",
            phrases: ["It is okay to pause.", "I will continue when I am ready.", "Thank you for your patience.", "Let me say that again.", "I have something important to share.", "I can take my time.", "Speaking takes courage.", "Every conversation helps me grow.", "I do not give up.", "I keep moving forward."],
            repeatCount: 3,
            speakText: "It is okay to pause. I can take my time."
          },
          {
            id: "u10-l2-3",
            title: "Reading",
            kind: "reading",
            description: "Read the passage three times with warmth and encouragement.",
            readText: "Some days speaking will feel easier than others. That is normal. Progress is not a straight line. Every time I choose to participate instead of staying silent, I strengthen my confidence and resilience.",
            durationHint: "Read three times.",
            speakText: "Some days speaking will feel easier than others. That is normal."
          },
          {
            id: "u10-l2-4",
            title: "Conversation Challenge",
            kind: "conversation",
            description: "Retell a recent conversation that felt difficult, then reflect on what happened and what you would do differently next time.",
            prompt: "Speak for five minutes. Include what happened, how you responded, what went well, and what you would do differently next time.",
            durationHint: "Speak for five minutes.",
            speakText: "A recent conversation felt difficult because I felt rushed, but I still shared my idea and kept going."
          }
        ]
      },
      {
        id: "unit-10-lesson-3",
        title: "Lesson 30 — Graduation Day",
        goal: "Celebrate your progress and prepare for confident communication beyond LanSpeech.",
        description: "Take one final breath, affirm your growth, and record a message to your future self.",
        durationMins: 14,
        coachTip: "This may be the end of the course, but it is only the beginning of your story.",
        techniqueReminders: ["🎓 Celebrate Your Growth", "🫁 Breathe Before You Speak", "🌟 Choose Connection Over Fear"],
        reflectionPrompt: "What do you want to remember about this journey when you look back on it later?",
        exercises: [
          {
            id: "u10-l3-1",
            title: "One Final Breath",
            kind: "breathing",
            description: "Take ten slow belly breaths and think about the first day you opened LanSpeech.",
            instructions: ["Take ten slow belly breaths.", "Notice how far you have come.", "Smile.", "Remember that your voice matters."],
            repeatCount: 10,
            speakText: "I am proud of how far I have come."
          },
          {
            id: "u10-l3-2",
            title: "Repeat After Me",
            kind: "repeat",
            description: "Practice the affirmations that mark this graduation moment.",
            phrases: ["My voice matters.", "My ideas matter.", "I deserve to participate.", "I communicate with courage.", "Every conversation is progress.", "I no longer wait for perfect fluency.", "I choose connection over fear.", "I believe in myself.", "My journey continues.", "I am ready."],
            repeatCount: 3,
            speakText: "My voice matters. I am ready."
          },
          {
            id: "u10-l3-3",
            title: "Reading",
            kind: "reading",
            description: "Read the passage three times as though you are speaking to your future self.",
            readText: "Thirty lessons ago, I began a journey toward more confident communication. Along the way I learned to breathe calmly, begin gently, speak smoothly, and trust my voice. More importantly, I discovered that my value has never depended on perfect fluency. My ideas, experiences, and dreams deserve to be heard. Every conversation from this day forward is another opportunity to grow.",
            durationHint: "Read three times.",
            speakText: "Thirty lessons ago, I began a journey toward more confident communication."
          },
          {
            id: "u10-l3-4",
            title: "Final Conversation Challenge",
            kind: "conversation",
            description: "Record a ten minute conversation about yourself and your future.",
            prompt: "Include who you are today, the goals you are working toward, what you learned during this course, a challenge you overcame, someone who inspires you, and one dream you refuse to give up on.",
            durationHint: "Record your response and keep it as a reminder of how far you have come.",
            speakText: "I am a confident communicator now, and I will keep growing with every conversation I have."
          }
        ]
      }
    ]
  },
];

export function getAllLessons() {
  let lessonCounter = 0;
  return units.flatMap(unit => unit.lessons.map((lesson) => {
    lessonCounter += 1;
    return {
      id: lesson.id,
      day_number: lessonCounter,
      title: lesson.title,
      description: lesson.description,
      duration_mins: lesson.durationMins,
      level: 'beginner',
      module: unit.title,
      practice_phrase: lesson.exercises.find(ex => ex.speakText)?.speakText ?? null,
      is_bonus: false,
      order_index: lessonCounter,
      unit_id: unit.id,
      unit_title: unit.title,
      unit_theme: unit.theme,
      unit_goal: unit.goal,
      goal: lesson.goal,
      coachTip: lesson.coachTip,
      techniqueReminders: lesson.techniqueReminders,
      exercises: lesson.exercises,
      reflection_prompt: lesson.reflectionPrompt,
    };
  }));
}

export function getLessonById(id: string): Lesson | null {
  return getAllLessons().find(lesson => lesson.id === id) ?? null;
}

export function getUnitLessons(unitId: string) {
  return getAllLessons().filter(lesson => lesson.unit_id === unitId);
}

export function getNextLesson(currentLessonId: string) {
  const lessons = getAllLessons();
  const currentIndex = lessons.findIndex(lesson => lesson.id === currentLessonId);
  return currentIndex >= 0 && currentIndex < lessons.length - 1 ? lessons[currentIndex + 1] : null;
}

export function getUnits() {
  let lessonCounter = 0;
  return units.map(unit => ({
    ...unit,
    lessons: unit.lessons.map((lesson, index) => {
      lessonCounter += 1;
      return {
        id: lesson.id,
        day_number: index + 1,
        title: lesson.title,
        description: lesson.description,
        duration_mins: lesson.durationMins,
        level: 'beginner',
        module: unit.title,
        practice_phrase: lesson.exercises.find(ex => ex.speakText)?.speakText ?? null,
        is_bonus: false,
        order_index: lessonCounter,
        unit_id: unit.id,
        unit_title: unit.title,
        unit_theme: unit.theme,
        unit_goal: unit.goal,
        goal: lesson.goal,
        coachTip: lesson.coachTip,
        techniqueReminders: lesson.techniqueReminders,
        exercises: lesson.exercises,
        reflection_prompt: lesson.reflectionPrompt,
      };
    }),
  }));
}
